### ISSUE TITLE
mixed language target

### ISSUE THREAD

**Issue by bhase** [joeyates/rake-builder#24]
Hi,

what would be the best way to handle targets which consist of more languages?

For example, using CppUTest for C uses C++ for the tests and test environment, but the implementation is done in C. You can see an example in my HP03S project, which compiles a test executable and a library (if you have CppUTest available), each file with the according compiler: cpp files witih g++, c files with gcc. This is handled in the Makefile.

Does it make sense to look up the compiler dynamically on runtime, depending on the extension of the source file? How would you handle such a situation?

**Comment by joeyates** [comment]
Closing due too inactivity.
